version: "3.7"

services:

  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=promadmin
      - GF_SECURITY_ADMIN_PASSWORD=prometheus
      - GF_USERS_ALLOW_SIGN_UP=false

  pushgateway:
    image: prom/pushgateway:v1.1.0
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped

  cadvisor:
    # image: gcr.io/google-containers/cadvisor:v0.34.0
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    ports:
      - "8080:8080"
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter
    container_name: blackbox
    volumes:
      - ./config:/config
    command:
      - "--config.file=/config/blackbox.yaml"
      - "--history.limit=50"

    ports:
      - "9115:9115"
    restart: unless-stopped

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - /etc/prometheus:/etc/prometheus
  #     - /Users/rajasekar.s1/Desktop/prometheus/data:/prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #     - "--storage.tsdb.path=/prometheus"
  #     - "--web.console.templates=/etc/prometheus/consoles"
  #     - "--web.console.libraries=/etc/prometheus/console-libraries"
  #     - "--web.enable-lifecycle"
  #   ports:
  #     - "9090:9090"
  #   restart: unless-stopped

  # nodeexporter:
  #   image: prom/node-exporter
  #   container_name: nodeexporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs/ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.ignored-mount-points'
#      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/"
    # ports:
    #   - "9100:9100"
    # restart: unless-stopped

volumes:
  grafana_data: